### ISSUE TITLE
Environment failing to Deploy - enableSolutionAndAlerts - Create-NewSolutionAndRulesFromList.ps1: line 44

### ISSUE THREAD

**Issue by JelaniB-sec** [Azure/Azure-Sentinel#11329]
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'. (Code: ResourceDeploymentFailure)
The provided script failed with the following error:
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
at , /mnt/azscripts/azscriptinput/Create-NewSolutionAndRulesFromList.ps1: line 44
at , : line 1
at , /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 310. Please refer to
https://aka.ms/DeploymentScriptsTroubleshoot
for more deployment script information. (Code: DeploymentScriptError)

To Reproduce
Simply deploy the Template it WILL fail.

Expected behavior
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'. (Code: ResourceDeploymentFailure)
The provided script failed with the following error:
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
at , /mnt/azscripts/azscriptinput/Create-NewSolutionAndRulesFromList.ps1: line 44
at , : line 1
at , /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 310. Please refer to
https://aka.ms/DeploymentScriptsTroubleshoot
for more deployment script information. (Code: DeploymentScriptError)

Please refer the Screenshot, @pemontto

Screenshots

image![Image](https://github.com/user-attachments/assets/bec0b195-fe5f-4f93-b4a6-cc373151441a)

**Comment by WVDAdminTF** [comment]
Hi @JelaniB-sec 
please do not expect any change since this issue is existing since **1 week of September**, some random person will respond to you in 1-2 weeks to try again, with doing any actual fixes.

![Image](https://github.com/user-attachments/assets/4b00cdf5-c230-40dc-ba01-68c27edcca86)

![Image](https://github.com/user-attachments/assets/ddae6899-081a-43c5-9d3e-33b935a1b06b)

**Comment by v-rusraut** [comment]
Hi @WVDAdminTF , Is your issue resolved, or did you make any changes during deployment to resolve it?

**Comment by JelaniB-sec** [comment]
@v-rusraut yep still experiencing this issue on my end fyi

**Comment by lussierd16** [comment]
I had this same issue when I would run this and passing a parameters file. I fixed this by changing one of the inputs for the "enabelSolutions1P" to "Entra ID" instead of "Azure AD". I found that on some old tenants "Azure AD" works but with newer tenants it needs "Entra ID".

**Comment by JelaniB-sec** [comment]
@lussierd16 Can you provide some more clarity on where you changed the input?
I added a commit that was intended to use that naming convention change, but still experiencing the same issue.
https://github.com/JelaniB-sec/Azure-Sentinel/commit/04365732a5230d14a903c90ea0964e7c74d4c28b

Any further help would be greatly appreciated

**Comment by v-sudkharat** [comment]
Tagging author - @pemontto

**Comment by JelaniB-sec** [comment]
@v-sudkharat thank you, I will await further correspondance

**Comment by v-sudkharat** [comment]
@a-balde, Still waiting for the author's response on this issue.

**Comment by v-sudkharat** [comment]
@a-balde, In addition, we are also checking this issue with our concern team as well, to get it unblocked.

**Comment by fishslime** [comment]
Is there a way to manually execute this "deployRules" step? Everything else succeeds except this issue. I've re-tried a dozen times using different parameters.

**Comment by JelaniB-sec** [comment]
any update on this? @v-sudkharat

**Comment by v-sudkharat** [comment]
@JelaniB-sec, We have shared this issue with concern team and team is currently working on troubleshooting of script. Once we get any info on it will update you. Thanks!

**Comment by v-sudkharat** [comment]
@JelaniB-sec / @a-balde / @fishslime, We have raised the PR with fix, meantime could you please deploy the template from below shared readme file and let us know if still facing the same issue : 

File link : -https://github.com/Azure/Azure-Sentinel/blob/762d0ebbcb32de84802a9ec01cd6332eef848d93/Tools/Sentinel-All-In-One/README.md

![Image](https://github.com/user-attachments/assets/2820daa8-f5e2-419d-bd84-ea4505cac1e6)


Many Thanks!

**Comment by v-sudkharat** [comment]
Hi @fishslime / @a-balde / @JelaniB-sec,  
Waiting for your response on above comment. Thanks!

**Comment by JelaniB-sec** [comment]
> Hi [@fishslime](https://github.com/fishslime) / [@a-balde](https://github.com/a-balde) / [@JelaniB-sec](https://github.com/JelaniB-sec), Waiting for your response on above comment. Thanks!

I was able to get this working by deploying through readme.md

**Comment by a-balde** [comment]
Hi @v-sudkharat, deployment from the provided link below worked.
File link : -https://github.com/Azure/Azure-Sentinel/blob/762d0ebbcb32de84802a9ec01cd6332eef848d93/Tools/Sentinel-All-In-One/README.md
