### ISSUE TITLE
Qualys VM Detection - Run.p1 fails

### ISSUE THREAD

**Issue by activex** [Azure/Azure-Sentinel#2842]
Deployed the function app via the template. Getting the below on each run where new detection have been found

`Connected!
2021-08-16T04:32:51  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2021-08-16T04:32:55.325 [Information] OUTPUT:
2021-08-16T04:33:31.273 [Information] OUTPUT: xml                            SIMPLE_RETURN
2021-08-16T04:33:31.276 [Information] OUTPUT: ---                            -------------
2021-08-16T04:33:31.276 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:33:31.278 [Information] OUTPUT: 3 hosts with detection found
2021-08-16T04:33:32.731 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:33:32.936 [Error] ERROR: Invoke-WebRequest : {"Error":"InvalidAuthorization","Message":"An invalid signature was specified in the Authorization header"}At C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1:161 char:18+ ... $response = Invoke-WebRequest -Uri $logAnalyticsUri -Method $method - ...+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\u2026application/json}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommandScript stack trace:at Post-LogAnalyticsData, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 161at <ScriptBlock>, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 232Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 403 (Forbidden).at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Invoke-WebRequest : {"Error":"InvalidAuthorization","Message":"An invalid signature was specified in the Authorization header"}At C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1:161 char:18+ ... $response = Invoke-WebRequest -Uri $logAnalyticsUri -Method $method - ...+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\u2026application/json}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommandScript stack trace:at Post-LogAnalyticsData, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 161at <ScriptBlock>, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 232Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 403 (Forbidden).at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Exception: Response status code does not indicate success: 403 (Forbidden).Stack:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2021-08-16T04:33:33.017 [Error] ERROR: Trace-PipelineObject : Cannot bind argument to parameter 'InputObject' because it is null.+ CategoryInfo          : InvalidData: (:) [Trace-PipelineObject], ParameterBindingValidationException+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Functions.PowerShellWorker.Commands.TracePipelineObjectCommandScript stack trace:at Post-LogAnalyticsData, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 162at <ScriptBlock>, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 232System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is null.at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Trace-PipelineObject : Cannot bind argument to parameter 'InputObject' because it is null.+ CategoryInfo          : InvalidData: (:) [Trace-PipelineObject], ParameterBindingValidationException+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Functions.PowerShellWorker.Commands.TracePipelineObjectCommandScript stack trace:at Post-LogAnalyticsData, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 162at <ScriptBlock>, C:\home\site\wwwroot\AzureFunctionQualysVM\run.ps1: line 232System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is null.at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()Exception: Cannot bind argument to parameter 'InputObject' because it is null.Stack:    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()
2021-08-16T04:33:33.081 [Information] OUTPUT:
2021-08-16T04:33:33.082 [Information] Executed 'Functions.AzureFunctionQualysVM' (Succeeded, Id=54a37217-XXXXXXX, Duration=42864ms)
2021-08-16T04:34:51  No new trace in the past 1 min(s).
2021-08-16T04:35:00.010 [Information] Executing 'Functions.AzureFunctionQualysVM' (Reason='Timer fired at 2021-08-16T04:35:00.0098580+00:00', Id=8d5899ce-be6e-4620-9c4f-18781239afc5)
2021-08-16T04:35:01.556 [Information] OUTPUT:
2021-08-16T04:35:04.957 [Information] OUTPUT: xml                            SIMPLE_RETURN
2021-08-16T04:35:04.965 [Information] OUTPUT: ---                            -------------
2021-08-16T04:35:04.966 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:35:04.967 [Information] OUTPUT: 0 hosts with detection found
2021-08-16T04:35:05.861 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:35:05.862 [Information] INFORMATION: No new results found for this interval
2021-08-16T04:35:05.863 [Information] OUTPUT:
2021-08-16T04:35:05.863 [Information] Executed 'Functions.AzureFunctionQualysVM' (Succeeded, Id=8d5899ce-XXXXXXX, Duration=5853ms)
2021-08-16T04:36:51  No new trace in the past 1 min(s).
2021-08-16T04:37:51  No new trace in the past 2 min(s).
2021-08-16T04:38:51  No new trace in the past 3 min(s).
2021-08-16T04:39:51  No new trace in the past 4 min(s).
2021-08-16T04:39:59.998 [Information] Executing 'Functions.AzureFunctionQualysVM' (Reason='Timer fired at 2021-08-16T04:39:59.9983571+00:00', Id=9f578433-XXXXXXXXX)
2021-08-16T04:40:01.743 [Information] OUTPUT:
2021-08-16T04:40:05.064 [Information] OUTPUT: xml                            SIMPLE_RETURN
2021-08-16T04:40:05.126 [Information] OUTPUT: ---                            -------------
2021-08-16T04:40:05.127 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:40:05.133 [Information] OUTPUT: 0 hosts with detection found
2021-08-16T04:40:06.131 [Information] OUTPUT: version="1.0" encoding="UTF-8" SIMPLE_RETURN
2021-08-16T04:40:06.132 [Information] INFORMATION: No new results found for this interval
2021-08-16T04:40:06.137 [Information] OUTPUT:
2021-08-16T04:40:06.140 [Information] Executed 'Functions.AzureFunctionQualysVM' (Succeeded, Id=9f578433-XXXXX, Duration=6141ms)
2021-08-16T04:41:51  No new trace in the past 1 min(s).`

**Comment by v-maudan** [comment]
@activex, I have fixed this issue  https://github.com/Azure/Azure-Sentinel/pull/2868.
Can you please deploy once or restrat the azure function. let me know if you still facing any issue? Thanks!

**Comment by activex** [comment]
@v-maudan thanks a lot.
Just tried to re-deploy using the button on the connector page and get the following error:

`{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "There was a conflict. The remote name could not be resolved: 'qualysvmglxocXXXXX.file.core.windows.net'",
        "details": [
            {
                "message": "There was a conflict. The remote name could not be resolved: 'qualysvmglxocXXXXX.file.core.windows.net'"
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}`

**Comment by activex** [comment]
All working now, thank you @v-maudan 
Can you check the QualysKB integration as well? I suspect there's the same issue.

**Comment by v-maudan** [comment]
@activex, Thanks for your confirmation, I have verified QualysKB integration which looks good. Thanks!
